---
- name: Installer les dépendances système
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present
    update_cache: yes

- name: Copier le code de la voting-app
  ansible.builtin.copy:
    src: azure-vote/
    dest: /app/
    mode: '0755'

- name: Installer les dépendances Python
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    state: present
    extra_args: "--break-system-packages"
